name: 'Mihomo Docker Build'
description: 'Build and publish Mihomo proxy service container'

inputs:
  mihomo_version:
    description: 'Mihomo core version tag'
    required: true
    default: 'v1.18.0'
  metacubexd_version:
    description: 'Metacubexd UI version'
    required: false
    default: 'latest'
  registry:
    description: 'Target container registry'
    required: true
    default: 'ghcr.io'

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.mihomo_version }}
    - ${{ inputs.metacubexd_version }}
    - ${{ inputs.registry }}

branding:
  icon: 'package'
  color: 'blue'